config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "seasons#home"

    resources :seasons#, only: [:index, :show]
    resources :plants#, only: [:index, :show, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :season
end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :plants
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    @plants = Plant.all
  end

  def show
    @plant = Plant.find(params[:id])
  end

  def new
    #@season = Season.find(params[:season_id])
    @plant = Plant.new
    @season_name = Season.all.map { |season| season.name }
  end

  def edit
      @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    @plant.update(plant_params)
    redirect_to plant_path(@plant)
  end

  def plant_params
    params.require(:plant).permit(:name, :season_id, :height, :width, :hardiness, :minsoiltemp, :depth, :separation, :watering, :fertilizing, :maturity, :production, :harvest, :img_url)
  end

  def create
    # @season = Season.find(params[:season_id])
    @plant = Plant.new(plant_params)
#    @plant.season = Season.find_by(name: params[:plant][:season])
    @plant.save
    redirect_to plants_path
  end

  def destroy
Plant.find(params[:id]).destroy
    redirect_to "/plants"
  end

  def plant_params
    params.require(:plant).permit(:name, :season_id, :height, :width, :hardiness, :minsoiltemp, :depth, :separation, :watering, :fertilizing, :maturity, :production, :harvest, :img_url)
  end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def index
    @seasons = Season.all
  end

  def home
  end

  def show
    @seasons = Season.find(params[:id])
  end

end

private
def season_params
  params.require(:season).permit(:name, :img_url)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Garden Buddy </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </head>

  <div class="wrapper">
  <header class="header">
    <a href="/"><div id="head">Garden Buddy</div></a>
  </header>
  <nav>
    <%= link_to "Seasons", seasons_path %> | <%= link_to "Plant Catalogue", plants_path %>
  </nav>
  <body>

    <aside class="aside aside-1">
      <br>
      <%= link_to "Plant Catalogue", plants_path %>

      <hr />

      <%= link_to "Seasons", seasons_path %><br>
      <br>
      <a href="/seasons/1">Early Spring</a><br>
      <a href="/seasons/2">Spring</a><br>
      <a href="/seasons/3">Late Spring</a><br>
      <a href="/seasons/4">Early Summer</a><br>
      <a href="/seasons/5">Summer</a><br>
      <a href="/seasons/6">Late Summer</a><br>
      <a href="/seasons/7">Early Fall</a></li><br>
      <a href="/seasons/8">Fall</a></li><br>
      <a href="/seasons/9">Late Fall</a><br>
      <a href="/seasons/10">Early Winter</a><br>
      <a href="/seasons/11">Winter</a><br>
    </aside>

    <main class="main">
      <%= yield %>
    </main>
  </body>

  <footer class="footer">Copywrite 2017. All rights reserved.
  </footer>
</div>
</html>

app/views/plants/edit.html.erb
<h2>Edit this plant</h2>

<%= form_for (@plant) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :height%>
  <%= f.text_field :height %>

  <%= f.label :width %>
  <%= f.text_field :width %>

  <%= collection_select(:plant, :season_id, Season.all, :id, :name) %>
  <%#= f.label :season %>
  <%#= f.text_field :season %>

  <%= f.label :hardiness %>
  <%= f.text_field :hardiness %>

  <%= f.label :depth %>
  <%= f.text_field :depth %>

  <%= f.label :separation %>
  <%= f.text_field :separation %>

  <%= f.label :watering %>
  <%= f.text_field :watering %>

  <%= f.label :fertilizing %>
  <%= f.text_field :fertilizing %>

  <%= f.label :maturity %>
  <%= f.text_field :maturity %>

  <%= f.label :production %>
  <%= f.text_field :production %>

  <%= f.label :harvest %>
  <%= f.text_field :harvest %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit "Save changes"%>

<% end %>
<br>
<br>
<%= form_for [@season, @plant], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>

<% end %>

app/views/plants/index.html.erb
<h1>Plant Catalogue</h1>
<h3><%= link_to 'Add a Plant', new_plant_path%></h3>
<% @plants.each do |plant| %>
  <div class="w3-card-4", "plant">

    <div class="w3-container" >
      <img src="<%= plant.img_url %>"/>
      <h2><%= link_to plant.name, plant%> - <%= plant.season.name %></h2>

      <div>
        <div  id="plant_data">Plant Height: <%= plant.height %> in.</div>
        <div id="plant_data">Plant Width: <%= plant.width %> in.</div>
        <div id="plant_data">Hardiness: <%= plant.hardiness %></div>
        <div id="plant_data">Planting Depth: <%= plant.depth %> in.</div>
        <div id="plant_data">Separation: <%= plant.separation %> in.</div>
        <div id="plant_data">Watering: <%= plant.watering %></div>
        <div id="plant_data">Fertilizing: <%= plant.fertilizing %></div>
        <div id="plant_data">Plant Maturity: <%= plant.maturity %> days</div>
        <div id="plant_data">Productive: <%= plant.production %> days</div>
        <div id="plant_data">Harvesting Inst.: <%= plant.harvest %></div>
      </div>
    </div>
  </div>
<% end %>

app/views/plants/new.html.erb
<h2>New Plant</h2>

<%= form_for @plant do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :height%>
  <%= f.text_field :height %>

  <%= f.label :width %>
  <%= f.text_field :width %>

  <%= collection_select(:plant, :season_id, Season.all, :id, :name) %>

  <%#= collection_select(
    :plant,
    :season,

    Season.all,
    :id,
    :name,
    )%>



  <%= f.label :hardiness %>
  <%= f.text_field :hardiness %>

  <%= f.label :depth %>
  <%= f.text_field :depth %>

  <%= f.label :separation %>
  <%= f.text_field :separation %>

  <%= f.label :watering %>
  <%= f.text_field :watering %>

  <%= f.label :fertilizing %>
  <%= f.text_field :fertilizing %>

  <%= f.label :maturity %>
  <%= f.text_field :maturity %>

  <%= f.label :production %>
  <%= f.text_field :production %>

  <%= f.label :harvest %>
  <%= f.text_field :harvest %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit "Add to Catalogue" %>
<% end %>

app/views/plants/show.html.erb
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>

<h1><%= @plant.name %></h1>
<h3><%= link_to 'Edit', edit_plant_path%></h3>
<h3><%= link_to 'Delete', plant_path, :method => :delete, data: {confirm: 'Are you sure?'}%></h3>

<div class="w3-card-4", "plant">

  <div class="w3-container" >
    <img src="<%= @plant.img_url %>"/>
    <div>
      <div  id="plant_data">Plant Height: <%= @plant.height %> in.</div>
      <div id="plant_data">Plant Width: <%= @plant.width %> in.</div>
      <div id="plant_data">Hardiness: <%= @plant.hardiness %></div>
      <div id="plant_data">Planting Depth: <%= @plant.depth %> in.</div>
      <div id="plant_data">Separation: <%= @plant.separation %> in.</div>
      <div id="plant_data">Watering: <%= @plant.watering %></div>
      <div id="plant_data">Fertilizing: <%= @plant.fertilizing %></div>
      <div id="plant_data">Plant Maturity: <%= @plant.maturity %> days</div>
      <div id="plant_data">Productive: <%= @plant.production %> days</div>
      <div id="plant_data">Harvesting Inst.: <%= @plant.harvest %></div>
    </div>

  </div>
</div>

app/views/seasons/home.html.erb
<h1> Welcome to Garden Buddy </h1>
<p> This application was designed to help you plan for, establish, <br>
   maintain and harvest a beautiful and productive garden. Plants are listed by recommended <br>
   planting season or you can simply explore our Plant Catalogue to learn more about all of the plants currently on our list.<br>

app/views/seasons/index.html.erb
<h1>Seasons</h1>
<% @seasons.each do |season| %>
  <div class="season">
    <h2><%= link_to season.name, season %></h2>
    <img src="<%= season.img_url %>"/>
  </div>
<% end %>

app/views/seasons/show.html.erb
<h1><%= @seasons.name %></h1>
<% @seasons.plants.each do |plant| %>
<div class="w3-card-4", "plant">

  <div class="w3-container" >
    <img src="<%= plant.img_url %>"/>
    <h2><%= link_to plant.name, plant%>

    <div>
      <div  id="plant_data">Plant Height: <%= plant.height %> in.</div>
      <div id="plant_data">Plant Width: <%= plant.width %> in.</div>
      <div id="plant_data">Hardiness: <%= plant.hardiness %></div>
      <div id="plant_data">Planting Depth: <%= plant.depth %> in.</div>
      <div id="plant_data">Separation: <%= plant.separation %> in.</div>
      <div id="plant_data">Watering: <%= plant.watering %></div>
      <div id="plant_data">Fertilizing: <%= plant.fertilizing %></div>
      <div id="plant_data">Plant Maturity: <%= plant.maturity %> days</div>
      <div id="plant_data">Productive: <%= plant.production %> days</div>
      <div id="plant_data">Harvesting Inst.: <%= plant.harvest %></div>
    </div>

  </div>
</div>
<% end %>